### ISSUE TITLE
vue-router @RouteParam NavigationDuplicated

### ISSUE THREAD

**Issue by melistik** [propero-oss/vue-extra-decorators#1]
Seems to be an issue in case of default use:

Code sample
```javascript
export default class Balance extends Vue {

    @RouteParam("workerId")
    private workerId?: string;

    @RouteQuery("from", { default: format(defaultFrom, "yyyy-MM") })
    private from?: string;

    @RouteQuery("to", { default: format(defaultTo, "yyyy-MM") })
    private to?: string;
```

Stacktrace console:
```javascript
vue-router.esm.js?8c4f:2051 Uncaught (in promise) 
NavigationDuplicated {_name: "NavigationDuplicated", name: "NavigationDuplicated", message: "Navigating to current location ("/balance/wney1e4y?to=2019-11&from=2019-01") is not allowed", stack: "Error↵    at new NavigationDuplicated (webpack-int…node_modules/vue/dist/vue.runtime.esm.js:4556:19)"}
message: "Navigating to current location ("/balance/wney1e4y?to=2019-11&from=2019-01") is not allowed"
name: "NavigationDuplicated"
_name: "NavigationDuplicated"
stack: "Error↵    at new NavigationDuplicated (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:1975:14)↵    at HTML5History.confirmTransition (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2091:18)↵    at HTML5History.transitionTo (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2035:8)↵    at HTML5History.replace (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2378:10)↵    at eval (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2793:22)↵    at new Promise (<anonymous>)↵    at VueRouter.replace (webpack-internal:///./node_modules/vue-router/dist/vue-router.esm.js:2792:12)↵    at VueComponent.eval [as to] (webpack-internal:///./node_modules/@propero/vue-extra-decorators/dist/main.esm.js:1976:22)↵    at VueComponent.updateTo (webpack-internal:///./node_modules/cache-loader/dist/cjs.js?!./node_modules/ts-loader/index.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/pages/Balance.vue?vue&type=script&lang=ts&:51:17)↵    at Watcher.run (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4556:19)"
__proto__: Error
```

**Comment by noramass** [comment]
In vue-router if you try to navigate to the same route you originated from, it throws an error.
In version 2.0.0 and following versions, a check is performed beforehand if the (serialized) value has changed or not and will prevent navigation in that case.
